In [2]:
# dodawanie
3 + 7

10

In [4]:
# odejmowanie
2 - 7

-5

In [5]:
#mnożenie
4 * 6

24

In [6]:
#dzielenie
9 / 3

3.0

In [11]:
#potęgowanie
8 ** 2

64

In [7]:
x = 10

In [12]:
print('Prezes jest moim szczęściem')

Prezes jest moim szczęściem


In [8]:
x

10

In [9]:
print(x)

10


In [14]:
rocznik = 1991

In [15]:
rocznik

1991

In [16]:
print(rocznik)

1991


In [17]:
teraz = 2018

In [18]:
teraz

2018

In [19]:
ile_lat = teraz - rocznik

In [20]:
print(ile_lat)

27


In [22]:
type(ile_lat)

int

In [23]:
zarobki = 5.50

In [24]:
zarobki

5.5

In [26]:
print(zarobki)

5.5


In [25]:
type(zarobki)

float

In [27]:
werdykt = 'To są marne zarobki'

In [28]:
werdykt

'To są marne zarobki'

In [29]:
type(werdykt)

str

In [30]:
werdykt + werdykt

'To są marne zarobkiTo są marne zarobki'

In [31]:
werdykt + ' Panie Prezesie'

'To są marne zarobki Panie Prezesie'

In [32]:
print('Urodziłem się w', rocznik)

Urodziłem się w 1991


In [33]:
werdykt

'To są marne zarobki'

In [34]:
print(werdykt)

To są marne zarobki


In [35]:
rocznik

1991

In [36]:
print(rocznik)

1991


In [37]:
info = 'Zarabiam na rękę' + zarobki

TypeError: must be str, not float

In [38]:
zarobki

5.5

In [39]:
str(zarobki)

'5.5'

In [42]:
info = 'Zarabiam na rękę ' + str(zarobki)

In [43]:
info

'Zarabiam na rękę 5.5'

In [44]:
wiek_info = 'Mam {} lat'.format(ile_lat)

In [45]:
wiek_info

'Mam 27 lat'

In [107]:
monolog = 'Niby jestem stary. \
Urodziłem się w {} i mam {} lat,\
ale wciąż zarabiam {} na godzinę.'.format(rocznik,
                                         ile_lat,
                                         zarobki)

In [108]:
monolog

'Niby jestem stary. Urodziłem się w 1991 i mam 27 lat,ale wciąż zarabiam 5.5 na godzinę.'

In [48]:
numer = '300'

In [49]:
numer + 30

TypeError: must be str, not int

In [50]:
int(numer)

300

In [51]:
werdykt

'To są marne zarobki'

In [52]:
int(werdykt)

ValueError: invalid literal for int() with base 10: 'To są marne zarobki'

In [53]:
pkt = '30.8'

In [54]:
float(pkt)

30.8

In [55]:
True

True

In [56]:
False

False

In [57]:
prawda = True

In [58]:
print(prawda)

True


In [59]:
type(prawda)

bool

In [60]:
prawda + prawda 

2

In [61]:
False + False 

0

In [63]:
wartosci = 2,3

In [65]:
[]

[]

In [66]:
list()

[]

In [67]:
moja_lista = ['Samsung', 'Huawei', 'Xiaomi']

In [68]:
moja_lista

['Samsung', 'Huawei', 'Xiaomi']

In [69]:
aj = 'Apple'

In [70]:
aj

'Apple'

In [71]:
moja_lista2 = ['Samsung', 'Huawei', 'Xiaomi', aj]

In [72]:
moja_lista2

['Samsung', 'Huawei', 'Xiaomi', 'Apple']

In [73]:
niemoja_lista = ['Polonez', 'Trabant', 'Warszawa']

In [74]:
lista = moja_lista2 + niemoja_lista

In [75]:
lista

['Samsung', 'Huawei', 'Xiaomi', 'Apple', 'Polonez', 'Trabant', 'Warszawa']

In [76]:
lista[1]

'Huawei'

In [77]:
lista[0]

'Samsung'

In [79]:
lista[3]

'Apple'

In [80]:
lista[0:3]

['Samsung', 'Huawei', 'Xiaomi']

In [81]:
lista[0:4]

['Samsung', 'Huawei', 'Xiaomi', 'Apple']

In [83]:
lista[1:3]

['Huawei', 'Xiaomi']

In [84]:
chinese = lista[1:3]

In [85]:
chinese

['Huawei', 'Xiaomi']

In [87]:
chinese[0][0]

'H'

In [90]:
chinese[0][0:3]

'Hua'

In [92]:
chinese[1][:3]

'Xia'

In [94]:
chinese[1][3:]

'omi'

In [95]:
#Witam serdecznie w bardze mlecznym.
ruskie = 4.50
ziemniaczki = 2.35
surowka = 2.15
nalesniki = 7.50
kompot = 2.00
kotlecik = 8.50
pomidorowa = 2.35
leniwe = 3.90
kasza = 2.25
wodka_spod_lady = 4.00

In [96]:
ceny = [ruskie, ziemniaczki, surowka,
        nalesniki, kompot, kotlecik,
       pomidorowa, leniwe, kasza, wodka_spod_lady]

In [97]:
ceny

[4.5, 2.35, 2.15, 7.5, 2.0, 8.5, 2.35, 3.9, 2.25, 4.0]

In [98]:
type(ceny)

list

In [99]:
type(ceny[0])

float

In [100]:
menu = ['ruskie', ruskie,
       'ziemniaczki', ziemniaczki,
       'surowka', surowka]

In [101]:
menu

['ruskie', 4.5, 'ziemniaczki', 2.35, 'surowka', 2.15]

In [104]:
menu2 = [['ruskie', ruskie],['ziemniaczki', ziemniaczki],
        ['surowka', surowka]]

In [105]:
menu2

[['ruskie', 4.5], ['ziemniaczki', 2.35], ['surowka', 2.15]]

In [106]:
len(menu2)

3

In [110]:
menu2[0][1]

4.5

In [112]:
menu2[-1]

['surowka', 2.15]

In [113]:
menu2

[['ruskie', 4.5], ['ziemniaczki', 2.35], ['surowka', 2.15]]

In [116]:
menu2[1][0] = 'kotlet nieznanego pochodzenia'

In [117]:
menu2

[['ruskie', 4.5], ['kotlet nieznanego pochodzenia', 2.35], ['surowka', 2.15]]

In [118]:
rachunek = menu2[0][1] + menu2[1][1] + menu2[-1][1]

In [119]:
rachunek

9.0

In [121]:
ceny

[4.5, 2.35, 2.15, 7.5, 2.0, 8.5, 2.35, 3.9, 2.25, 4.0]

In [122]:
?sorted

In [123]:
sorted(ceny)

[2.0, 2.15, 2.25, 2.35, 2.35, 3.9, 4.0, 4.5, 7.5, 8.5]

In [124]:
sorted(ceny,reverse=True)

[8.5, 7.5, 4.5, 4.0, 3.9, 2.35, 2.35, 2.25, 2.15, 2.0]

In [125]:
ceny

[4.5, 2.35, 2.15, 7.5, 2.0, 8.5, 2.35, 3.9, 2.25, 4.0]

In [126]:
ceny_sort = sorted(ceny,reverse=True)

In [127]:
ceny_sort

[8.5, 7.5, 4.5, 4.0, 3.9, 2.35, 2.35, 2.25, 2.15, 2.0]

In [128]:
rozpacz = 'To jest krzyk rozpaczy!'

In [129]:
rozpacz.upper()

'TO JEST KRZYK ROZPACZY!'

In [130]:
rozpacz

'To jest krzyk rozpaczy!'

In [131]:
rozpacz = rozpacz.upper()

In [132]:
rozpacz

'TO JEST KRZYK ROZPACZY!'

In [134]:
rozpacz.count('O')

2

In [135]:
ceny

[4.5, 2.35, 2.15, 7.5, 2.0, 8.5, 2.35, 3.9, 2.25, 4.0]

In [136]:
ceny.index(8.5)

5

In [137]:
ceny[5]

8.5

In [138]:
ceny.count(2.35)

2

In [139]:
ceny.index(2.35)

1

In [140]:
ceny.count('2.35')

0

In [142]:
ceny

[4.5, 2.35, 2.15, 7.5, 2.0, 8.5, 2.35, 3.9, 2.25, 4.0]

In [143]:
ceny + 7.35

TypeError: can only concatenate list (not "float") to list

In [148]:
ceny.append(7.35)

In [149]:
ceny

[4.5, 2.35, 2.15, 7.5, 2.0, 8.5, 2.35, 3.9, 2.25, 4.0, 7.35, 7.35, 7.35]

In [152]:
ceny.pop(-1)

7.35

In [153]:
ceny

[4.5, 2.35, 2.15, 7.5, 2.0, 8.5, 2.35, 3.9, 2.25, 4.0, 7.35]

In [154]:
nowe_pozycje = [7.35, 4.50, 5.55, 6.7]

In [155]:
ceny.append(nowe_pozycje)

In [156]:
ceny

[4.5,
 2.35,
 2.15,
 7.5,
 2.0,
 8.5,
 2.35,
 3.9,
 2.25,
 4.0,
 7.35,
 [7.35, 4.5, 5.55, 6.7]]

In [157]:
ceny.pop(-1)

[7.35, 4.5, 5.55, 6.7]

In [158]:
ceny

[4.5, 2.35, 2.15, 7.5, 2.0, 8.5, 2.35, 3.9, 2.25, 4.0, 7.35]

In [159]:
ceny.extend(nowe_pozycje)

In [160]:
ceny

[4.5,
 2.35,
 2.15,
 7.5,
 2.0,
 8.5,
 2.35,
 3.9,
 2.25,
 4.0,
 7.35,
 7.35,
 4.5,
 5.55,
 6.7]

In [163]:
ceny[-4:]

[7.35, 4.5, 5.55, 6.7]

In [164]:
del ceny[-4:]

In [166]:
ceny

[4.5, 2.35, 2.15, 7.5, 2.0, 8.5, 2.35, 3.9, 2.25, 4.0, 7.35]

In [167]:
ceny.remove(2.35)

In [168]:
ceny

[4.5, 2.15, 7.5, 2.0, 8.5, 2.35, 3.9, 2.25, 4.0, 7.35]

In [169]:
ceny.reverse()

In [170]:
ceny

[7.35, 4.0, 2.25, 3.9, 2.35, 8.5, 2.0, 7.5, 2.15, 4.5]

##### importowanie pakietów i funkcji

In [171]:
import os

In [174]:
gdzie_jestem = os.getcwd()

In [175]:
type(gdzie_jestem)

str

In [176]:
gdzie_jestem

'/Users/Gacek/Documents/Koło neuro - warsztaty'

In [177]:
from os import listdir

In [178]:
listdir()

['.ipynb_checkpoints', 'Spotkanie_1.ipynb']

In [179]:
listdir('/Users/Gacek/Documents/')

['.DS_Store',
 '.ipynb_checkpoints',
 '.localized',
 'Artykuły',
 'Biblioteka.indl',
 'cvkasienki.docx',
 'DTI',
 'efile',
 'efile-backup',
 'files',
 'GitHub',
 'IBM',
 'Insanity',
 'Koła',
 'Koło neuro - warsztaty',
 'Książki',
 'MATLAB',
 'Mendeley Desktop',
 'Neuro',
 'Paradox Interactive',
 'Portugalski',
 'Postery i prezentacje',
 'Praktyki',
 'Procedura OK 2.zip',
 'Prywatne',
 'PsychoPy',
 'Python',
 'R',
 'Statystyka',
 'Urzędowe']

In [181]:
sc_windows = r'C:\Users\Putin\Photos\KGB Party 1985'

In [182]:
sc_windows

'C:\\Users\\Putin\\Photos\\KGB Party 1985'

In [183]:
prezes = 150

In [184]:
prezes > 180

False

In [185]:
prezes < 140

False

In [186]:
prezes > 145

True

In [187]:
prezes == 160

False

In [188]:
prezes

150

In [189]:
prezes != 0

True

In [190]:
import numpy as np

In [192]:
seed = np.random.RandomState(100)
wzrost_lista = list(seed.normal(loc=1.70,
                                scale=.15,size=100000).round(2))
seed2 = np.random.RandomState(100)
waga_lista = list(seed2.normal(loc=80,
                               scale=10,size=100000).round(2))

In [193]:
wzrost_lista

[1.4399999999999999,
 1.75,
 1.8700000000000001,
 1.6599999999999999,
 1.8500000000000001,
 1.78,
 1.73,
 1.54,
 1.6699999999999999,
 1.74,
 1.6299999999999999,
 1.77,
 1.6100000000000001,
 1.8200000000000001,
 1.8,
 1.6799999999999999,
 1.6200000000000001,
 1.8500000000000001,
 1.6299999999999999,
 1.53,
 1.9399999999999999,
 1.9299999999999999,
 1.6599999999999999,
 1.5700000000000001,
 1.73,
 1.8400000000000001,
 1.8100000000000001,
 1.8999999999999999,
 1.6499999999999999,
 1.71,
 1.73,
 1.48,
 1.5900000000000001,
 1.8200000000000001,
 1.8100000000000001,
 1.6299999999999999,
 1.8799999999999999,
 1.45,
 1.5,
 1.52,
 1.6200000000000001,
 1.6000000000000001,
 1.7,
 1.6100000000000001,
 1.8899999999999999,
 1.4399999999999999,
 1.55,
 1.75,
 1.46,
 1.9199999999999999,
 1.52,
 1.6200000000000001,
 1.5600000000000001,
 1.5800000000000001,
 1.72,
 1.78,
 1.5700000000000001,
 1.8899999999999999,
 1.6899999999999999,
 1.5700000000000001,
 1.5700000000000001,
 1.7,
 1.74,
 1.7,
 1.45,
 1.5

In [194]:
bmi = waga_lista / wzrost_lista**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [197]:
xyz = [3, 5, 9]

In [198]:
xyz2 = np.array([3, 5, 9])

In [199]:
xyz * 2

[3, 5, 9, 3, 5, 9]

In [200]:
xyz2 * 2

array([ 6, 10, 18])

In [201]:
lista = ['Beata', 5550, True]

In [202]:
lista

['Beata', 5550, True]

In [203]:
np.array(lista)

array(['Beata', '5550', 'True'],
      dtype='<U5')

In [205]:
waga_lista[:5] + waga_lista[:5]

[62.5,
 83.430000000000007,
 91.530000000000001,
 77.480000000000004,
 89.810000000000002,
 62.5,
 83.430000000000007,
 91.530000000000001,
 77.480000000000004,
 89.810000000000002]

In [206]:
waga_lista[:5] + 10

TypeError: can only concatenate list (not "int") to list

In [207]:
waga = np.array(waga_lista)

In [208]:
waga

array([ 62.5 ,  83.43,  91.53, ...,  60.33,  85.4 ,  85.17])

In [209]:
wzrost = np.array(wzrost_lista)

In [210]:
wzrost

array([ 1.44,  1.75,  1.87, ...,  1.4 ,  1.78,  1.78])

In [212]:
waga[:5] + waga[:5]

array([ 125.  ,  166.86,  183.06,  154.96,  179.62])

In [213]:
waga[:5] + 10

array([  72.5 ,   93.43,  101.53,   87.48,   99.81])

In [215]:
wzrost_lista > 1.60

TypeError: '>' not supported between instances of 'list' and 'float'

In [216]:
wzrost > 1.60

array([False,  True,  True, ..., False,  True,  True], dtype=bool)

In [217]:
wzrost

array([ 1.44,  1.75,  1.87, ...,  1.4 ,  1.78,  1.78])

In [219]:
selekcja = wzrost[wzrost > 1.60]

In [220]:
len(selekcja)

73912

In [222]:
prezes2 = 1500100900269743657312979853579834656
kot = 456763463687463597834296548632874784

In [223]:
prezes2 > kot

True

In [224]:
selekcja_waga = waga[wzrost > 1.60]

In [225]:
selekcja_waga

array([ 83.43,  91.53,  77.48, ...,  77.3 ,  85.4 ,  85.17])

In [226]:
len(selekcja_waga)

73912

In [227]:
bmi = waga / wzrost**2

In [228]:
bmi

array([ 30.1408179 ,  27.24244898,  26.1746118 , ...,  30.78061224,
        26.95366747,  26.88107562])

In [235]:
jak_oni_zyja = bmi >= 30

In [236]:
jak_oni_zyja

array([ True, False, False, ...,  True, False, False], dtype=bool)

In [238]:
wzrost[jak_oni_zyja]

array([ 1.44,  1.45,  1.44, ...,  1.44,  1.37,  1.4 ])

In [239]:
wzrost[bmi >= 30]

array([ 1.44,  1.45,  1.44, ...,  1.44,  1.37,  1.4 ])

In [ ]:
wzrost >= 1.60
wzrost <= 1.80

In [241]:
bmi_sredniacy = bmi[(wzrost >= 1.60) & (wzrost <= 1.80)]

In [242]:
bmi_sredniacy

array([ 27.24244898,  28.11728843,  26.87160712, ...,  28.0519669 ,
        26.95366747,  26.88107562])

In [245]:
bmi_sredniacy = bmi_sredniacy.round(1)

In [246]:
bmi_sredniacy

array([ 27.2,  28.1,  26.9, ...,  28.1,  27. ,  26.9])